adding php8 and updating mando command with additional helpers

diff --git a/bin/mando b/bin/mando
--- a/bin/mando
+++ b/bin/mando
@@ -268,6 +268,57 @@ if [ $# -gt 0 ]; then
             mando_is_not_running
         fi
 
+    elif [ "$1" == "xdebug" ]; then
+        shift 1
+
+        if [ "$1" == "on" ]; then
+            docker-compose exec \
+                "$CONTAINER_WEB" \
+                phpenmod xdebug
+        elif [ "$1" == "off" ]; then
+            docker-compose exec \
+                "$CONTAINER_WEB" \
+                phpdismod xdebug
+        else
+            echo -e "${WHITE}Invalid Command.${NC}" >&2
+            echo "" >&2
+            echo -e "${WHITE}You may enable/disable xdebug using the following commands:${NC} 'mando xdebug on' or 'mando xdebug off '" >&2
+            exit 1
+        fi
+
+
+    elif [ "$1" == "package:composer" ]; then
+        shift 1
+
+        PACKAGE="$1"
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                -u developer \
+                -w "/app/packages/$PACKAGE" \
+                "$CONTAINER_WEB" \
+                composer "$@"
+        else
+            mando_is_not_running
+        fi
+
+    elif [ "$1" == "package:test" ]; then
+        shift 1
+
+        PACKAGE="$1"
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                -u developer \
+                -w "/app/packages/$PACKAGE" \
+                "$CONTAINER_WEB" \
+                ./vendor/bin/phpunit "$@"
+        else
+            mando_is_not_running
+        fi
+
     elif [ "$1" == "up" ]; then
         shift 1
         docker-compose up -d "$@"
